### ISSUE TITLE
Festify plays one song, then plays whatever album I last played in spotify

### ISSUE THREAD

**Issue by ccantill** [Festify/app#290] opened 2020-01-17 12:14 UTC
Yesterday I played Bach's Cello Suite in Spotify on my phone at home. Today I started playing our Festify playlist in the office on my laptop (as per usual on Fridays), and after the first song it started playing Bach's Cello Suite. Skipping just played the next song in that album. I had to open my Spotify client, clear out the queue, reload Festify and then it played the next song. But the same thing happened again the song after that. Every time a new song plays in Festify, the queue gets filled again with whatever album I played last in the Spotify client and I'm having to manual clear it.

**Comment by ccantill** [comment] 2020-01-17 16:06
As a pretty shitty workaround I made a playlist with just Monty Python's Dennis Moore Song (Pt3) and played that. Now in between every song it sings "Dennis Moore, Dennis Moore is not in this bit" but that only takes 3 seconds. Playlist here: https://open.spotify.com/playlist/3BAx0z3JGEE4taDIGdjP2D?si=vZMyI7YTRFeuOgPHBilKTA

**Comment by leolabs** [comment] 2020-01-17 16:41
That's an interesting bug! Could you give me more details on which OS and Browser you're using Festify on? Do you have any instances of Spotify running while using Festify? This shouldn't be a problem but maybe it's connected to that.

**Comment by DeastinY** [comment] 2020-01-18 14:43
Hi all, we also run into the same issue. OS and Browser information will follow.

**Comment by ccantill** [comment] 2020-01-18 16:06
I'm running Chrome on Linux (Ubuntu 19.10). I've tried with both Spotify running and without. I even changed my password and logged out all devices to be sure but that didn't change it.

**Comment by DeastinY** [comment] 2020-01-18 16:15
It's strange that this happened without any code changes, right?
It's also browser/OS agnostic so that would pretty much only leave spotify as the culprit, but:
https://developer.spotify.com/community/news/ there doesn't seem to be anything relevant

**Comment by NeoLegends** [comment] 2020-01-18 16:16
This is strange in particular because Festify is not supposed to interact with the queue at all. When a song ends and the next one starts we send a command to Spotify to play this specific one song. Perhaps that behavior has changed?

**Comment by DeastinY** [comment] 2020-01-18 16:17
Could it be that you've been using some beta api commands that were changed?

**Comment by ccantill** [comment] 2020-01-18 16:17
It doesn't seem to realize that the song has ended, probably because Spotify is automatically adding that other stuff to the queue and just keeps playing?

**Comment by DeastinY** [comment] 2020-01-18 16:20
Shouldn't you see behaviour like this in the logs?

**Comment by DeastinY** [comment] 2020-01-18 20:41
We somehow broke it even more. 
Two votes now also skips a track 😅

**Comment by GisliNielsen** [comment] 2020-01-18 21:53
Happens to me as well, not a lone wolf scenario

**Comment by DeastinY** [comment] 2020-01-18 22:02
Apparently only exactly two vote songs are skipped.

**Comment by jannomeister** [comment] 2020-01-20 01:37
same here :( It plays my anime songs after the last song from festify played.

**Comment by pasathaioum5** [comment] 2020-01-20 02:46
same here... having this issue since Friday

**Comment by Cross-roads** [comment] 2020-01-20 11:41
I can also confirm this issue ... first noticed friday evening.

**Comment by benb7760** [comment] 2020-01-20 12:35
I have the same issue. If, in Festify, I click the next button manually it will start playing correctly. If I allow the song to play out it just reverts to whatever is in my 'Next Up' queue in spotify. 

Coincidentally, I have told Spotify not to auto play suggestions when music ends, yet this 'Next Up' queue still seems to exist. Unsure if that is related

**Comment by benb7760** [comment] 2020-01-20 12:43
@leolabs I think I have more detail on what the exact cause of the issue is.

1. I queue three songs in Festify and begin the playback. The first song begins playing
2. During first song, I look at spotify and see there are random items in next up, which have come from the last time i was using spotify. I remove these and have an empty next up queue.
3. The first song completes. The second song begins correctly (yay!) but the Next Up queue gets refilled with nonsense.
4. The second song completes and spotify begins playing the next up queue instead of the third song from Festify.
5. If I now allow the next up queue to run to completion, festify begins playing the third song
6. Then spotify next up takes over again

**Comment by NeoLegends** [comment] 2020-01-20 12:47
@leolabs Seems like we do not interpret the end of the song correctly and then don't start the next one. WDYT?

**Comment by leolabs** [comment] 2020-01-20 12:54
@NeoLegends yup, that seems to be the problem. I think that the events from Spotify‘s Web SDK may have changed, so our heuristics don’t work properly anymore. It may be a better idea to regularly fetch the current playback position and work with timers like jqbx.fm does it.

**Comment by NeoLegends** [comment] 2020-01-20 12:56
https://github.com/Festify/niceify-web-playback-sdk we should probably finish that

**Comment by benb7760** [comment] 2020-01-20 14:12
For anybody looking for an non ideal workaround; Create a playlist with one song. Shortest possible song you can find! I found one which is only 4 seconds long via a quick google search. Play this playlist, then start using Festify. The queue will work but there will be a 4 second song between each. Not ideal at all but it at least restores some usability.

**Comment by Cross-roads** [comment] 2020-01-20 17:01
There is a song called 'One second of Silence' from 'Quality assured hipsters' which is really -hence the title- one second of silence. So that results in nearly perfect playback. Only a small delay

**Comment by leolabs** [comment] 2020-01-21 19:13
I've expanded the conditions for when to skip to the next track. As soon as Festify notices that the current progress is smaller than the last progress (new track means progress === 0), the player is paused so the track from up next isn't played, and the next track from the queue is played.

Please tell me if this workaround works for you. It should be online now :)

**Comment by leolabs** [comment] 2020-01-21 19:27
@DeastinY could you check if the double-skipping bug you've experienced still occurs or if it has been fixed by this as well?

**Comment by DeastinY** [comment] 2020-01-22 11:11
thanks for the fast fix, will check when I have time :)

**Comment by jannomeister** [comment] 2020-01-23 02:40
after the latest patch, the songs wont play :( I'm using the latest version of firefox browser

**Comment by jannomeister** [comment] 2020-01-23 02:41
When I play the very first song in the queue it will play my spotify latest song :(

**Comment by pasathaioum5** [comment] 2020-01-23 02:50
Still having #290 issue have to use the quick dirty hack method 
(see the gif below)
![festify](https://user-images.githubusercontent.com/9591497/72952864-c7504680-3dc5-11ea-842a-bf9e6b15a922.gif)

**Comment by pasathaioum5** [comment] 2020-01-23 03:39
even worst, now the website will occationally freeze the music will stop playing and the browser saying "Tab is not responsding "Festify" what would you like to do" and gave me option to wait or close 

![festify2](https://user-images.githubusercontent.com/9591497/72954896-97587180-3dcc-11ea-8981-0e3a81f36373.gif)

**Comment by ccantill** [comment] 2020-01-24 06:25
Definitely not fixed for me either. Now I even have to close Festify to be able to play anything in the Spotify client.

**Comment by chrisbjw** [comment] 2020-01-24 15:20
Same Problem. Workaround with the "one Second of silence" isn't working either. It's just bursting through the playlist silent.

**Comment by leolabs** [comment] 2020-01-24 16:15
Oh man, okay. I've rolled back the update for now. Please clear your browser cache and try again. 

@NeoLegends do you have time for a remote session in the beginning of February? We should get this bug fixed asap, but I think we'll be quicker with four eyes :)

**Comment by chrisbjw** [comment] 2020-01-24 16:22
Nice! Now the work around is working again!

**Comment by b12e** [comment] 2020-02-14 15:54
What's the latest on this bug?

**Comment by leolabs** [comment] 2020-02-15 13:22
We‘re still on it and will dedicate some more time on it next week. It’s
more complicated than we thought it would be.

**Comment by pasathaioum5** [comment] 2020-02-16 12:19
Wait, I thought it was already fixed. I used it since you rolled back the update and it works fine so far for me 😂

**Comment by leolabs** [comment] 2020-02-17 00:09
Oh, that's interesting! I'll take a closer look on Tuesday. Maybe Spotify reversed some changes they made to their API or something 🤔

**Comment by pasathaioum5** [comment] 2020-02-17 01:58
![festify_ok](https://user-images.githubusercontent.com/9591497/74618244-76810300-5163-11ea-9cdd-aa1349a36f61.gif)

some gif to confirm it's ok

**Comment by jannomeister** [comment] 2020-02-17 03:35
@leolabs yeah, I thought its already fixed because its working now :) The bug was gone.

**Closed** 2020-12-10 17:31 UTC
