### ISSUE TITLE
No audio on rasbian buster

### ISSUE THREAD

**Issue by MarioGirotti** [Festify/app#293] opened 2020-02-24 18:55 UTC
On rasbian buster neither with chromium nor with firefox brower I get any audio output from festify. Us. Progressbar of track is running but no sound is audible. 
Usual webstreams (web radio) plays flawless with this setup. So audio setup of rasbian /raspberry pi is fine.

**Comment by leolabs** [comment] 2020-02-24 19:18
Just to check, does Spotify's [Web Player](https://open.spotify.com) work? If it does, it's likely an error on our end, if not, it might be a problem with either Spotify or your setup.

**Comment by MarioGirotti** [comment] 2020-02-25 18:41
Just tried the webplayer and also this does not work. Actually I cannot even open the webplayer. Sporify complains that I must enable an option in chromium to be able to play DRM content... (which I already have enabled).

**Comment by leolabs** [comment] 2020-02-26 16:52
Then that'll be the problem since Festify uses the same API. Maybe you can see if you can get Spotify's Web Player to work on Raspbian and when that works try to use Festify again. Unfortunately, I don't have a Raspberry Pi here to try to reproduce the errors, but when you get it to work, please do report back how you did it :)

**Comment by MarioGirotti** [comment] 2020-02-26 19:04
I googled a bit and figured out that chromium builds on ARM lacks libwidevine. Luckily there is a short guide (https://blog.vpetkov.net/2019/07/12/netflix-and-spotify-on-a-raspberry-pi-4-with-latest-default-chromium/) how to fix this. 
Now festify works perfectly on my raspberry pi.

**Comment by leolabs** [comment] 2020-02-27 10:55
That's awesome! I'll close this issue for now as the problem has been fixed, but please feel free to open a new one if you encounter any future problems.

**Closed by leolabs** 2020-02-27 10:55 UTC
